{
 "title": "MLE-дашборд",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Распределение предсказаний модели",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "real_estate_app_predictions_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Квантили времени запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, http_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, http_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, http_request_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение запросов по видам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}